apiVersion: apps/v1
kind: Deployment
metadata:
 name: sample-springboot-app
 labels:
   app: sample-springboot-app
spec:
 selector:
   matchLabels:
     app: sample-springboot-app
 template:
   metadata:
      labels:
        app: sample-springboot-app
      annotations:                               ### here
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /internal/metrics
   spec:
     containers:
     - image: anilsakr/springboot-kubenetes
       name: springboot-chat
       imagePullPolicy: IfNotPresent
       ports:
         - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  annotations:
           prometheus.io/scrape: 'true'
           filter.by.port.name: 'true'
  name: sample-springboot-app-svc
spec:
    ports:
    - name: sample-springboot-app
      targetPort: 8080
      port: 8080
      nodePort: 30205
      protocol: TCP
    selector:
      app: sample-springboot-app
    type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-springboot-app
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: sample-springboot-app
  endpoints:
  - port: api
    path: '/actuator/prometheus'
    interval: 10s
    honorLabels: true

